### ISSUE TITLE
Check changes on websites that require login/interaction

### ISSUE THREAD

**Issue by ahumaydan** [marcveens/homebridge-website-change-check#5]
Not so much an issue, more of a feature request. Specifically for [this website](https://www.communityvaccination.org/default.aspx) that requires interaction with two fields before a selector can be identified.

**Comment by marcveens** [comment]
Hi @ahumaydan, thanks for the feature request. Could you explain what interaction should take place on that website? Then I see if I can figure out a way to implement it

**Comment by ahumaydan** [comment]
Certainly. There are two interactions required:

1. Profession / Classification must be set via drop down menu to General Support
2. Event must be set to any item in the drop down menu

This will then trigger the CSS selector .ContentPlaceHolder1_UpdatePanelSchedule to appear, which I think is what I need to check for changes

**Comment by marcveens** [comment]
Thanks for the clarification! Will look into this soon

**Comment by marcveens** [comment]
This feature is added in v1.0.5 which I will release in a minute. If you use the following config all should be well:

```
{
    "changeChecks": [
        {
            "name": "communityvaccination",
            "url": "https://www.communityvaccination.org/default.aspx",
            "selector": "#ContentPlaceHolder1_UpdatePanelSchedule tr:nth-child(2)",
            "checkInterval": 300000,
            "stepsBeforeCheck": [
                {
                    "action": "setSelectValue",
                    "selector": "#ContentPlaceHolder1_DropDownListProfessions",
                    "value": "68"
                },
                {
                    "action": "waitForMilliseconds",
                    "value": "500"
                },
                {
                    "action": "setSelectValue",
                    "selector": "#ContentPlaceHolder1_DropDownListOpKey",
                    "value": "*"
                },
                {
                    "action": "waitForMilliseconds",
                    "value": "500"
                }
            ]
        }
    ],
    "platform": "WebsiteChangeCheck"
}
```

**Comment by ahumaydan** [comment]
Marc,

This is amazing. Thank you so much!

**Comment by marcveens** [comment]
Hi @ahumaydan, you might want to upgrade to v1.0.6 I just released. I noticed some stability issues with 1.0.5 when fetching data from the source you provided. 

Also using this configuration will help with preventing some timeouts:
```
{
    "changeChecks": [
        {
            "name": "communityvaccination",
            "url": "https://www.communityvaccination.org/default.aspx",
            "selector": "#ContentPlaceHolder1_UpdatePanelSchedule tr:nth-child(2)",
            "checkInterval": 300000,
            "stepsBeforeCheck": [
                {
                    "action": "setSelectValue",
                    "selector": "#ContentPlaceHolder1_DropDownListProfessions",
                    "value": "68"
                },
                {
                    "action": "waitForMilliseconds",
                    "value": "2000"
                },
                {
                    "action": "setSelectValue",
                    "selector": "#ContentPlaceHolder1_DropDownListOpKey",
                    "value": "*"
                }
            ]
        }
    ],
    "platform": "WebsiteChangeCheck"
}
```

**Comment by ahumaydan** [comment]
Wow, big improvement. Thank you. 

The * value only seems to be returning results for one of the options in #ContentPlaceHolder1_DropDownListOpKey. Any ideas how to fix that?

**Comment by marcveens** [comment]
Yes that's correct, it gets only the first available option of the select element. Unfortunately I can't loop and fetch results for all the options.. You might want to add multiple changeCheckers to check all the available options
